//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_28_7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemInfo
    {
        public int Member_ID { get; set; }
        public string Member_Name { get; set; }
        public Nullable<int> Member_Age { get; set; }
        public string Member_Img { get; set; }
    }
}
